# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://www.zmei.moe # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Zihan Mei's Personal Site
description: > # this means to ignore newlines until "Language & timezone"
  Welcome to my website! The site contains my projects and the research during 2014-2019, from the Bachelor of Architecture in Tsinghua University to the Master of Architecture in Urban Design in Harvard GSD.


## => Language and Timezone
##############################
lang: en # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Zihan Mei
  url       :
  avatar    : https://i.loli.net/2020/01/07/O5TDCs9NzyRwMYF.jpg # path or url of avatar image (square)
  bio       : I am an architecture graduated from Tsinghua University and currently studying for Master of Architecture in Urban Deisgn in Harvard GSD. I'm learning hand drawing, photography, guitar and coding by myself - all for the inspiration in design.
  email     : meizihanyx@gmail.com
  facebook  : zmzihanmei # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : #ZihanMei # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : #3311072445 # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: meizihanyx # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : Zephaniah_Mei # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : #mzh14 # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : #139195504 # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : zihan-mei-616b8b162 # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : saturn-drm # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: saturn-drm/saturn-drm.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: bootcdn # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addtoany # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: valine # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : TraYX5qatlF6M9zqBvwHacWS-MdYXbMMI # LeanCloud App id
    app_key     : 0Tpby3lCQIMgeX3vpVoLxU8v # LeanCloud App key
    placeholder : <(￣︶￣)> # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: leancloud # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : TraYX5qatlF6M9zqBvwHacWS-MdYXbMMI # LeanCloud App id
    app_key   : 0Tpby3lCQIMgeX3vpVoLxU8v # LeanCloud App key
    app_class : personalblog # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : UA-156998560-1 # Google Analytics id for the site
    anonymize_ip: true # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor
  - /specialfolder
  - /_site

# collections_dir: /
collections:
  /:
    output: true
  projects:
    output: true
  posts:
    output: true
  essays:
    output: true
  image:
    output: true
  guitar:
    output: true
  zh:
    output: true
  digest:
    output: true
  coding:
    output: true

defaults:
#   ## home
#   - scope:
#       path: /
#     values:
#       articles:
#         excerpt_type: html
  ## posts
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## projects
  - scope:
      path: ""
      type: projects
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## essays
  - scope:
      path: ""
      type: essays
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## image
  - scope:
      path: ""
      type: image
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## guitar
  - scope:
      path: ""
      type: guitar
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## zh
  - scope:
      path: ""
      type: zh
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## digest
  - scope:
      path: ""
      type: digest
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true
  ## coding
  - scope:
      path: ""
      type: coding
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      # lightbox: true



## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji